services:
  parser:
    class: Symfony\Component\Yaml\Parser
    lazy: true
  finder:
    class: Symfony\Component\Finder\Finder
    lazy: true
  filesystem:
    class: Symfony\Component\Filesystem\Filesystem
    lazy: true
  yaml:
    class: Symfony\Component\Yaml\Yaml
    lazy: true
  config:
    class: Drupal\Console\Config
    arguments: ["@parser"]
  requirement_checker:
    class: Drupal\Console\Utils\RequirementChecker
    arguments: ["@parser"]
    lazy: true
  redbean:
    class: RedBeanPHP\R
    lazy: true
  annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader
    lazy: true
  annotation_apc_cache:
    class: Doctrine\Common\Cache\ApcCache
  annotation_cached_reader:
    class: Doctrine\Common\Annotations\CachedReader
    arguments: ["@annotation_reader", "@annotation_apc_cache", false]
    lazy: true
  command_dependency_resolver:
    class: Drupal\Console\Command\CommandDependencyResolver
    arguments: ["@annotation_cached_reader", "@helper_kernel"]

  file_util:
    class: Drupal\Console\Utils\File
    lazy: true
